username=Admin
password=admin123
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
browser=Chrome
DriverLocation="C:\\Users\\HARIKRISHNAN\\eclipse-workspace\\Session2\\TESTNGTDDFRAMEWORK\\chromedriver.exe"
