#root logger

#Appender

#Layout

#Root logger option
log4j.rootLogger=DEBUG, file
#configuration to print into file
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file=C:\\log\\logging.log
log4j.appender.file.MaxFileSize=12MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout  
log4j.appender.file.layout.conversionPattern=%m%n 
